pre_gauss:
    apply: true
    ksize_x: 5
    ksize_y: 5
    sigma_x: 1.5
    sigma_y: 1.5

canny:
    apply: true
    min_threshold: 60
    max_threshold: 145

post_gauss:
    apply: true
    ksize_x: 5
    ksize_y: 5
    sigma_x: 1.5
    sigma_y: 1.5

hough:
    dp: 2
    min_dist: 32
    param1: 120
    param2: 38
    min_radius: 5
    max_radius: 20

roi:
    x: 100
    y: 150
    width: 1720
    height: 850

visualize: true
